name: trigger gatsby-jimmy action

on:
  push:
    branches: [master, develop]

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2         

      - name: ECHO Variable
        run: |
          echo "${{ env.REF_VERSION }}"    

      - name: Master
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESSON_TOKENS }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jimmy010679/gatsby-jimmy/actions/workflows/node.js.yml/dispatches -d '{"ref":"develop"}'
